apiVersion: graphql.gloo.solo.io/v1alpha1
kind: GraphQLSchema
metadata:
  name: bookinfo-graphql
  namespace: gloo-system
spec:
  enableIntrospection: true
  resolutions:
  - matcher:
      fieldMatcher:
        field: productsForHome
        type: Query
    restResolver:
      requestTransform:
        headers:
          :method:
            typedProvider:
              value: GET
          :path:
            typedProvider:
              value: /api/v1/products
      upstreamRef:
        name: default-productpage-9080
        namespace: gloo-system
  - matcher:
      fieldMatcher:
        field: author
        type: Product
    restResolver:
      requestTransform:
        headers:
          :method:
            typedProvider:
              value: GET
          :path:
            graphqlParent:
              path:
                - key: id
            providerTemplate: /details/{}
      upstreamRef:
        name:  default-details-9080
        namespace: gloo-system
  - matcher:
      fieldMatcher:
        field: review
        type: Product
    restResolver:
      requestTransform:
        headers:
          :method:
            typedProvider:
              value: GET
          :path:
            graphqlParent:
              path:
                - key: id
            providerTemplate: /reviews/{}
      upstreamRef:
        name:  default-reviews-9080
        namespace: gloo-system
  - matcher:
      fieldMatcher:
        field: ratings
        type: Product
    restResolver:
      requestTransform:
        headers:
          :method:
            typedProvider:
              value: GET
          :path:
            graphqlParent:
              path:
                - key: id
            providerTemplate: /ratings/{}
      upstreamRef:
        name:  default-ratings-9080
        namespace: gloo-system
  schema: "
    type Query {
      productsForHome: [Product]
    }

    type Product {
      id: String
      title: String
      descriptionHtml: String
      author: String
      pages: Int
      year: Int
      review: ProductReview
      ratings: [Rating]
    }

    type ProductReview {
      reviews : [Review]
    }

    type Review {
      reviewer: String
      text: String
    }

    type Rating {
      reviewer: String
      numStars: Int
    }
    "